FROM quay.io/sara_banderby/rhel9-r4:shiny

LABEL maintainer="abanderb@redhat.com"
LABEL description="R runtime image for dashboard demo."
LABEL version="1.0"

USER root

RUN dnf -y install glibc-langpack-en
ENV LANG en_US.UTF-8

RUN R -q -e 'install.packages(c("skimr"), repos = "https://cran.rstudio.com/")'

RUN mkdir /application


COPY app.r /application
COPY datafile.csv /application

WORKDIR /application

USER 1001

EXPOSE 8080

ENTRYPOINT R -s -e 'library("shiny"); runApp(host = "0.0.0.0", port = 8080)'
