FROM registry.access.redhat.com/ubi9/ubi

LABEL maintainer="abanderb@redhat.com"
LABEL description="Runtime and libraries for the Password application"
LABEL version="1.5"

USER root

RUN dnf update -y

RUN dnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm && \
    /usr/bin/crb enable && \
    dnf install -y epel-release && \
    dnf install -y flexiblas-* && \
    dnf install -y https://mirror.stream.centos.org/9-stream/CRB/x86_64/os/Packages/openblas-openmp64-0.3.21-2.el9.x86_64.rpm && \
    dnf install -y https://mirror.stream.centos.org/9-stream/CRB/x86_64/os/Packages/flexiblas-openblas-openmp64-3.0.4-8.el9.x86_64.rpm && \
    dnf update -y


RUN dnf install -y https://rpmfind.net/linux/centos-stream/9-stream/BaseOS/x86_64/os/Packages/pkgconf-pkg-config-1.7.3-10.el9.x86_64.rpm && \
    dnf install -y https://mirror.stream.centos.org/9-stream/AppStream/x86_64/os/Packages/flexiblas-3.0.4-8.el9.x86_64.rpm && \
    dnf install -y libtirpc.x86_64 && \
    dnf install -y https://mirror.stream.centos.org/9-stream/AppStream/x86_64/os/Packages/perl-libs-5.32.1-480.el9.x86_64.rpm && \
    dnf install -y https://mirror.stream.centos.org/9-stream/AppStream/x86_64/os/Packages/perl-Unicode-EastAsianWidth-12.0-7.el9.noarch.rpm && \
    dnf install -y https://mirror.stream.centos.org/9-stream/CRB/x86_64/os/Packages/texinfo-6.7-15.el9.x86_64.rpm && \
    dnf install -y https://mirror.stream.centos.org/9-stream/CRB/x86_64/os/Packages/texinfo-tex-6.7-15.el9.x86_64.rpm && \
    dnf install -y https://rpmfind.net/linux/centos-stream/9-stream/CRB/x86_64/os/Packages/flexiblas-netlib64-3.0.4-8.el9.x86_64.rpm && \
    dnf install -y https://rpmfind.net/linux/centos-stream/9-stream/CRB/x86_64/os/Packages/flexiblas-devel-3.0.4-8.el9.x86_64.rpm && \
    dnf install -y https://rpmfind.net/linux/centos-stream/9-stream/CRB/x86_64/os/Packages/libtirpc-devel-1.3.3-9.el9.x86_64.rpm && \
    dnf update -y && \
    dnf install -y R && \
    dnf install -y libsodium-devel.x86_64 && \
    dnf install -y libgit2-devel.x86_64 && \
    dnf install -y libcurl-devel && \
    dnf install -y cmake

RUN R --version

USER 1001


